{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "36b8877ee28d4ba688fbf1564643f8d5": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "VBoxModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "VBoxModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "VBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_8171ef2262064a8da5707c2dc3949e79",
              "IPY_MODEL_41b603d91dba4cbcb5c0d09e82fb3eba",
              "IPY_MODEL_e518c2a4048b4796a8e31af06ed39d8e"
            ],
            "layout": "IPY_MODEL_14098273ad494549ba282756de7b5f9e"
          }
        },
        "8171ef2262064a8da5707c2dc3949e79": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ButtonView",
            "button_style": "",
            "description": "Raíces",
            "disabled": false,
            "icon": "",
            "layout": "IPY_MODEL_492e5d9d9df94a119b30243d6ae09f55",
            "style": "IPY_MODEL_c28d8915b8e7411585a4a03fede0bc72",
            "tooltip": ""
          }
        },
        "41b603d91dba4cbcb5c0d09e82fb3eba": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ButtonView",
            "button_style": "",
            "description": "Interpoladores",
            "disabled": false,
            "icon": "",
            "layout": "IPY_MODEL_bc6c1e5bdf7947faa65146fcb730f7a3",
            "style": "IPY_MODEL_ee51faa2bebc4d3b8e2d5b0fe80716d4",
            "tooltip": ""
          }
        },
        "e518c2a4048b4796a8e31af06ed39d8e": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ButtonView",
            "button_style": "",
            "description": "Integración",
            "disabled": false,
            "icon": "",
            "layout": "IPY_MODEL_6e7b17b7f2714b7e9e847a687fe92e66",
            "style": "IPY_MODEL_d782336cbdb743c2adb1bbe92c5b0739",
            "tooltip": ""
          }
        },
        "14098273ad494549ba282756de7b5f9e": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "492e5d9d9df94a119b30243d6ae09f55": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "c28d8915b8e7411585a4a03fede0bc72": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "button_color": null,
            "font_weight": ""
          }
        },
        "bc6c1e5bdf7947faa65146fcb730f7a3": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "ee51faa2bebc4d3b8e2d5b0fe80716d4": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "button_color": null,
            "font_weight": ""
          }
        },
        "6e7b17b7f2714b7e9e847a687fe92e66": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "d782336cbdb743c2adb1bbe92c5b0739": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "button_color": null,
            "font_weight": ""
          }
        },
        "c8a0f8cd248c44d388b90bda5ee90747": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ButtonView",
            "button_style": "",
            "description": "Bisección",
            "disabled": false,
            "icon": "",
            "layout": "IPY_MODEL_9fbb46166dcd45dcb604a27052c412b9",
            "style": "IPY_MODEL_180b24cbd6dc423195417316f8232ad7",
            "tooltip": ""
          }
        },
        "9fbb46166dcd45dcb604a27052c412b9": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "180b24cbd6dc423195417316f8232ad7": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "button_color": null,
            "font_weight": ""
          }
        },
        "21e1130707a94d3caea7e61c7be958df": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ButtonView",
            "button_style": "",
            "description": "Regla Falsa",
            "disabled": false,
            "icon": "",
            "layout": "IPY_MODEL_516f463d28e5452cbfefca9122b95d35",
            "style": "IPY_MODEL_eee91ebac1c34bb78c82d0596188da38",
            "tooltip": ""
          }
        },
        "516f463d28e5452cbfefca9122b95d35": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "eee91ebac1c34bb78c82d0596188da38": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "button_color": null,
            "font_weight": ""
          }
        },
        "e9caa74fbcd241e893006c3fd16c63f9": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ButtonView",
            "button_style": "",
            "description": "Newton-Raphson",
            "disabled": false,
            "icon": "",
            "layout": "IPY_MODEL_7ddacf7fe4874d7989643e915329a700",
            "style": "IPY_MODEL_c8562977b31243b79c63ba524d38b1ae",
            "tooltip": ""
          }
        },
        "7ddacf7fe4874d7989643e915329a700": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "c8562977b31243b79c63ba524d38b1ae": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "button_color": null,
            "font_weight": ""
          }
        },
        "3b425ca2df054e40a03e6fe84db4095d": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ButtonView",
            "button_style": "",
            "description": "Secante",
            "disabled": false,
            "icon": "",
            "layout": "IPY_MODEL_bfce75228d9d4fb29913d50094eed968",
            "style": "IPY_MODEL_d53800e82b884a86bfa8cf8f57ce0545",
            "tooltip": ""
          }
        },
        "bfce75228d9d4fb29913d50094eed968": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "d53800e82b884a86bfa8cf8f57ce0545": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "button_color": null,
            "font_weight": ""
          }
        },
        "2826d059c3474f019bf578dafb5be19b": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ButtonView",
            "button_style": "",
            "description": "Volver al Menú Principal",
            "disabled": false,
            "icon": "",
            "layout": "IPY_MODEL_d2bbd97d2f414265b018f227dd704eb6",
            "style": "IPY_MODEL_afc2d40152ea447e8d4dafd1952f4121",
            "tooltip": ""
          }
        },
        "d2bbd97d2f414265b018f227dd704eb6": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "afc2d40152ea447e8d4dafd1952f4121": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "button_color": null,
            "font_weight": ""
          }
        },
        "aa0f35b98ef44cb7aceae9144d87f1ba": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "TextModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "TextModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "TextView",
            "continuous_update": true,
            "description": "Función:",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_76bf3802dfb940ccba3ae7b15477e9ac",
            "placeholder": "​",
            "style": "IPY_MODEL_278e13710a0e46f38ab6046ea8c2ee50",
            "value": "x**3 - x - 2"
          }
        },
        "76bf3802dfb940ccba3ae7b15477e9ac": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "278e13710a0e46f38ab6046ea8c2ee50": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "14f169d66cd54c0294d6f1788dc13dc3": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "TextModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "TextModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "TextView",
            "continuous_update": true,
            "description": "Punto inicial (a):",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_edfe7263d1214e6d84e90bd46012f91f",
            "placeholder": "​",
            "style": "IPY_MODEL_9440e4713f874ceda4afeafdbd81eed4",
            "value": "1"
          }
        },
        "edfe7263d1214e6d84e90bd46012f91f": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "9440e4713f874ceda4afeafdbd81eed4": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "b3de2d7cdc684f67b73ca6e3bb045bfa": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "TextModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "TextModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "TextView",
            "continuous_update": true,
            "description": "Punto final (b):",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_05af3cc226564ca381006b4e3685efef",
            "placeholder": "​",
            "style": "IPY_MODEL_561c17cfd9e949a196a63f78281e387c",
            "value": "2"
          }
        },
        "05af3cc226564ca381006b4e3685efef": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "561c17cfd9e949a196a63f78281e387c": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "43a4b3d5bb094cf9af09a61f141e0011": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "TextModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "TextModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "TextView",
            "continuous_update": true,
            "description": "Tolerancia:",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_c4ba63890e0f4672899ecd2e628b4b39",
            "placeholder": "​",
            "style": "IPY_MODEL_80377ed170b04a96b4d8fcba16033366",
            "value": "1e-5"
          }
        },
        "c4ba63890e0f4672899ecd2e628b4b39": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "80377ed170b04a96b4d8fcba16033366": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "72be770cc8b74113b24f00185a2da652": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "TextModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "TextModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "TextView",
            "continuous_update": true,
            "description": "Iteraciones máximas:",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_e76e87ff20ef4dd88fc6d99721b03f3e",
            "placeholder": "​",
            "style": "IPY_MODEL_dd0642a14ca547cb9486e2f7d5354416",
            "value": "100"
          }
        },
        "e76e87ff20ef4dd88fc6d99721b03f3e": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "dd0642a14ca547cb9486e2f7d5354416": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "2579ccc1f5fc458ea79e9cbd4bedfbde": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ButtonView",
            "button_style": "",
            "description": "Ejecutar Regla Falsa",
            "disabled": false,
            "icon": "",
            "layout": "IPY_MODEL_62dd7864f4904ea9b062e3efacef1781",
            "style": "IPY_MODEL_cc1e1bd747f9439c84740c1679254edb",
            "tooltip": ""
          }
        },
        "62dd7864f4904ea9b062e3efacef1781": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "cc1e1bd747f9439c84740c1679254edb": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ButtonStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ButtonStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "button_color": null,
            "font_weight": ""
          }
        }
      }
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "import ipywidgets as widgets\n",
        "from IPython.display import display, clear_output\n",
        "import sympy as sp\n",
        "from sympy.parsing.sympy_parser import parse_expr\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "############# DEFINICION DE LAS FUNCIONES PARA CADA MÉTODO #####################\n",
        "\n",
        "\n",
        "# Función para el método de la bisección\n",
        "def bisection_method(f, a, b, tol, max_iter):\n",
        "    if f(a) * f(b) >= 0:\n",
        "        return \"El método de bisección no es aplicable. f(a) y f(b) deben tener signos opuestos.\", []\n",
        "\n",
        "    iter_count = 0\n",
        "    table_data = []\n",
        "    previous_fm = None\n",
        "\n",
        "    while (b - a) / 2.0 > tol and iter_count < max_iter:\n",
        "        midpoint = (a + b) / 2.0\n",
        "        fa = f(a)\n",
        "        fb = f(b)\n",
        "        fm = f(midpoint)\n",
        "\n",
        "        error = abs(fm - previous_fm) if previous_fm is not None else None\n",
        "        table_data.append([iter_count, a, b, midpoint, fa, fb, fa * fm, error])\n",
        "\n",
        "        if fm == 0:\n",
        "            return midpoint, table_data\n",
        "        elif fa * fm < 0:\n",
        "            b = midpoint\n",
        "        else:\n",
        "            a = midpoint\n",
        "\n",
        "        previous_fm = fm\n",
        "        iter_count += 1\n",
        "\n",
        "    return (a + b) / 2.0, table_data\n",
        "\n",
        "# Función para el método de la regla falsa\n",
        "def false_position_method(f, a, b, tol, max_iter):\n",
        "    if f(a) * f(b) >= 0:\n",
        "        return \"El método de la regla falsa no es aplicable. f(a) y f(b) deben tener signos opuestos.\", []\n",
        "\n",
        "    iter_count = 0\n",
        "    table_data = []\n",
        "\n",
        "    while (b - a) > tol and iter_count < max_iter:\n",
        "        fa = f(a)\n",
        "        fb = f(b)\n",
        "        c = b - (fb * (b - a) / (fb - fa))\n",
        "        fc = f(c)\n",
        "\n",
        "        table_data.append([iter_count, a, b, c, fa, fb, fc, abs(fc)])\n",
        "\n",
        "        if fc == 0:\n",
        "            return c, table_data\n",
        "        elif fa * fc < 0:\n",
        "            b = c\n",
        "        else:\n",
        "            a = c\n",
        "\n",
        "        iter_count += 1\n",
        "\n",
        "    return c, table_data\n",
        "\n",
        "# Función para el método de Newton-Raphson\n",
        "def newton_method(f, x0, tol, max_iter):\n",
        "    x = sp.symbols('x')\n",
        "    f_expr = parse_expr(input_function.value)\n",
        "    df = sp.diff(f_expr, x)\n",
        "    df = sp.lambdify(x, df)\n",
        "    iter_count = 0\n",
        "    table_data = []\n",
        "\n",
        "    while iter_count < max_iter:\n",
        "        fx = f(x0)\n",
        "        dfx = df(x0)\n",
        "        if dfx == 0:\n",
        "            return \"Derivada es cero. No se puede continuar.\", []\n",
        "\n",
        "        x1 = x0 - fx / dfx\n",
        "        error = abs(x1 - x0)\n",
        "        table_data.append([iter_count, x0, fx, dfx, error])\n",
        "\n",
        "        if error < tol:\n",
        "            return x1, table_data\n",
        "\n",
        "        x0 = x1\n",
        "        iter_count += 1\n",
        "\n",
        "    return x1, table_data\n",
        "\n",
        "# Función para el método de la secante\n",
        "def secant_method(f, x0, x1, tol, max_iter):\n",
        "    iter_count = 0\n",
        "    table_data = []\n",
        "\n",
        "    while iter_count < max_iter:\n",
        "        fx0 = f(x0)\n",
        "        fx1 = f(x1)\n",
        "        if fx1 - fx0 == 0:\n",
        "            return \"División por cero. No se puede continuar.\", []\n",
        "\n",
        "        x2 = x1 - fx1 * (x1 - x0) / (fx1 - fx0)\n",
        "        error = abs(x2 - x1)\n",
        "        table_data.append([iter_count, x0, x1, fx0, fx1, x2, error])\n",
        "\n",
        "        if error < tol:\n",
        "            return x2, table_data\n",
        "\n",
        "        x0, x1 = x1, x2\n",
        "        iter_count += 1\n",
        "\n",
        "    return x2, table_data\n",
        "\n",
        "################################################################################\n",
        "\n",
        "\n",
        "# Función para graficar la función y el punto hallado\n",
        "def plot_function_and_root(func, a, b, root):\n",
        "    x_vals = np.linspace(a, b, 400)\n",
        "    y_vals = [func(x) for x in x_vals]\n",
        "\n",
        "    plt.figure(figsize=(10, 6))\n",
        "    plt.plot(x_vals, y_vals, label='Función')\n",
        "    plt.axhline(0, color='black', linewidth=0.5)\n",
        "    plt.axvline(root, color='red', linestyle='--', label=f'Raíz: {root:.5f}')\n",
        "    plt.scatter(root, func(root), color='red')\n",
        "    plt.title('Gráfica de la Función y la Raíz Encontrada')\n",
        "    plt.xlabel('x')\n",
        "    plt.ylabel('f(x)')\n",
        "    plt.legend()\n",
        "    plt.grid(True)\n",
        "    plt.show()\n",
        "    display(button_back)\n",
        "# Función para manejar el clic en el botón de bisección\n",
        "def on_bisection_click(b):\n",
        "    clear_output(wait=True)\n",
        "    display(input_function)\n",
        "    display(input_a)\n",
        "    display(input_b)\n",
        "    display(input_tol)\n",
        "    display(input_iter)\n",
        "    display(button_execute_bisection)\n",
        "\n",
        "# Función para manejar el clic en el botón de regla falsa\n",
        "def on_false_position_click(b):\n",
        "    clear_output(wait=True)\n",
        "    display(input_function)\n",
        "    display(input_a)\n",
        "    display(input_b)\n",
        "    display(input_tol)\n",
        "    display(input_iter)\n",
        "    display(button_execute_false_position)\n",
        "\n",
        "# Función para manejar el clic en el botón de Newton-Raphson\n",
        "def on_newton_click(b):\n",
        "    clear_output(wait=True)\n",
        "    display(input_function)\n",
        "    display(input_x0)\n",
        "    display(input_tol)\n",
        "    display(input_iter)\n",
        "    display(button_execute_newton)\n",
        "\n",
        "# Función para manejar el clic en el botón de secante\n",
        "def on_secant_click(b):\n",
        "    clear_output(wait=True)\n",
        "    display(input_function)\n",
        "    display(input_x0)\n",
        "    display(input_x1)\n",
        "    display(input_tol)\n",
        "    display(input_iter)\n",
        "    display(button_execute_secant)\n",
        "\n",
        "\n",
        "########################## EJECUCION DE LOS MÉTODOS ############################\n",
        "\n",
        "\n",
        "# Función para ejecutar el método de la bisección con los datos ingresados por el usuario\n",
        "def execute_bisection(b):\n",
        "    func_str = input_function.value\n",
        "    x = sp.symbols('x')\n",
        "    func = sp.lambdify(x, parse_expr(func_str))\n",
        "    a = float(input_a.value)\n",
        "    b = float(input_b.value)\n",
        "    tol = float(input_tol.value)\n",
        "    max_iter = int(input_iter.value)\n",
        "\n",
        "    result, table_data = bisection_method(func, a, b, tol, max_iter)\n",
        "\n",
        "    # Mostrar la raíz encontrada\n",
        "    print(f\"La raíz encontrada es: {result}\")\n",
        "\n",
        "    # Crear y mostrar la tabla de resultados\n",
        "    columns = [\"Iteración\", \"a\", \"b\", \"Punto Medio\", \"f(a)\", \"f(b)\", \"f(a)*f(Punto Medio)\", \"Error\"]\n",
        "    df = pd.DataFrame(table_data, columns=columns)\n",
        "    display(df)\n",
        "\n",
        "    # Graficar la función y el punto hallado\n",
        "    plot_function_and_root(func, a, b, result)\n",
        "\n",
        "# Función para ejecutar el método de la regla falsa con los datos ingresados por el usuario\n",
        "def execute_false_position(b):\n",
        "    func_str = input_function.value\n",
        "    x = sp.symbols('x')\n",
        "    func = sp.lambdify(x, parse_expr(func_str))\n",
        "    a = float(input_a.value)\n",
        "    b = float(input_b.value)\n",
        "    tol = float(input_tol.value)\n",
        "    max_iter = int(input_iter.value)\n",
        "\n",
        "    result, table_data = false_position_method(func, a, b, tol, max_iter)\n",
        "\n",
        "    # Mostrar la raíz encontrada\n",
        "    print(f\"La raíz encontrada es: {result}\")\n",
        "\n",
        "    # Crear y mostrar la tabla de resultados\n",
        "    columns = [\"Iteración\", \"a\", \"b\", \"c\", \"f(a)\", \"f(b)\", \"f(c)\", \"Error\"]\n",
        "    df = pd.DataFrame(table_data, columns=columns)\n",
        "    display(df)\n",
        "\n",
        "    # Graficar la función y el punto hallado\n",
        "    plot_function_and_root(func, a, b, result)\n",
        "\n",
        "# Función para ejecutar el método de Newton-Raphson con los datos ingresados por el usuario\n",
        "def execute_newton(b):\n",
        "    func_str = input_function.value\n",
        "    x = sp.symbols('x')\n",
        "    func = sp.lambdify(x, parse_expr(func_str))\n",
        "    x0 = float(input_x0.value)\n",
        "    tol = float(input_tol.value)\n",
        "    max_iter = int(input_iter.value)\n",
        "\n",
        "    result, table_data = newton_method(func, x0, tol, max_iter)\n",
        "\n",
        "    # Mostrar la raíz encontrada\n",
        "    print(f\"La raíz encontrada es: {result}\")\n",
        "\n",
        "    # Crear y mostrar la tabla de resultados\n",
        "    columns = [\"Iteración\", \"x0\", \"f(x)\", \"f'(x)\", \"Error\"]\n",
        "    df = pd.DataFrame(table_data, columns=columns)\n",
        "    display(df)\n",
        "\n",
        "    # Graficar la función y el punto hallado\n",
        "    plot_function_and_root(func, x0 - 5, x0 + 5, result)\n",
        "\n",
        "# Función para ejecutar el método de la secante con los datos ingresados por el usuario\n",
        "def execute_secant(b):\n",
        "    func_str = input_function.value\n",
        "    x = sp.symbols('x')\n",
        "    func = sp.lambdify(x, parse_expr(func_str))\n",
        "    x0 = float(input_x0.value)\n",
        "    x1 = float(input_x1.value)\n",
        "    tol = float(input_tol.value)\n",
        "    max_iter = int(input_iter.value)\n",
        "\n",
        "    result, table_data = secant_method(func, x0, x1, tol, max_iter)\n",
        "\n",
        "    # Mostrar la raíz encontrada\n",
        "    print(f\"La raíz encontrada es: {result}\")\n",
        "\n",
        "    # Crear y mostrar la tabla de resultados\n",
        "    columns = [\"Iteración\", \"x0\", \"x1\", \"f(x0)\", \"f(x1)\", \"x2\", \"Error\"]\n",
        "    df = pd.DataFrame(table_data, columns=columns)\n",
        "    display(df)\n",
        "\n",
        "    # Graficar la función y el punto hallado\n",
        "    plot_function_and_root(func, min(x0, x1) - 5, max(x0, x1) + 5, result)\n",
        "\n",
        "# Función para mostrar los botones de los métodos de raíces\n",
        "def show_raices():\n",
        "    clear_output(wait=True)\n",
        "    display(button_bisection)\n",
        "    display(button_false_position)\n",
        "    display(button_newton)\n",
        "    display(button_secant)\n",
        "    display(button_back)\n",
        "\n",
        "# Función para manejar clics en el botón de volver al menú principal\n",
        "def back_to_menu(b):\n",
        "    clear_output(wait=True)\n",
        "    display(menu)\n",
        "\n",
        "# Widgets de entrada\n",
        "input_function = widgets.Text(value='x**3 - x - 2', description='Función:')\n",
        "input_a = widgets.Text(value='1', description='Punto inicial (a):')\n",
        "input_b = widgets.Text(value='2', description='Punto final (b):')\n",
        "input_x0 = widgets.Text(value='1', description='Punto inicial (x0):')\n",
        "input_x1 = widgets.Text(value='2', description='Punto inicial (x1):')\n",
        "input_tol = widgets.Text(value='1e-5', description='Tolerancia:')\n",
        "input_iter = widgets.Text(value='100', description='Iteraciones máximas:')\n",
        "\n",
        "# Botones para los métodos de raíces\n",
        "button_bisection = widgets.Button(description=\"Bisección\")\n",
        "button_bisection.on_click(on_bisection_click)\n",
        "button_false_position = widgets.Button(description=\"Regla Falsa\")\n",
        "button_false_position.on_click(on_false_position_click)\n",
        "button_newton = widgets.Button(description=\"Newton-Raphson\")\n",
        "button_newton.on_click(on_newton_click)\n",
        "button_secant = widgets.Button(description=\"Secante\")\n",
        "button_secant.on_click(on_secant_click)\n",
        "\n",
        "# Botones para ejecutar los métodos con los datos ingresados por el usuario\n",
        "button_execute_bisection = widgets.Button(description=\"Ejecutar Bisección\")\n",
        "button_execute_bisection.on_click(execute_bisection)\n",
        "button_execute_false_position = widgets.Button(description=\"Ejecutar Regla Falsa\")\n",
        "button_execute_false_position.on_click(execute_false_position)\n",
        "button_execute_newton = widgets.Button(description=\"Ejecutar Newton-Raphson\")\n",
        "button_execute_newton.on_click(execute_newton)\n",
        "button_execute_secant = widgets.Button(description=\"Ejecutar Secante\")\n",
        "button_execute_secant.on_click(execute_secant)\n",
        "\n",
        "# Botón para volver al menú principal\n",
        "button_back = widgets.Button(description=\"Volver al Menú Principal\")\n",
        "button_back.on_click(back_to_menu)\n",
        "\n",
        "# Mostrar el menú principal\n",
        "button_raices = widgets.Button(description=\"Raíces\")\n",
        "button_interpoladores = widgets.Button(description=\"Interpoladores\")\n",
        "button_integracion = widgets.Button(description=\"Integración\")\n",
        "\n",
        "# Funciones para manejar clics en los botones del menú principal\n",
        "def show_raices_handler(b):\n",
        "    show_raices()\n",
        "\n",
        "def show_empty(b):\n",
        "    clear_output(wait=True)\n",
        "    print(\"Funcionalidad no implementada aún.\")\n",
        "\n",
        "button_raices.on_click(show_raices_handler)\n",
        "button_interpoladores.on_click(show_empty)\n",
        "button_integracion.on_click(show_empty)\n",
        "\n",
        "# Contenedor para los botones del menú principal\n",
        "menu = widgets.VBox([button_raices, button_interpoladores, button_integracion])\n",
        "\n",
        "# Mostrar el menú\n",
        "display(menu)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 113,
          "referenced_widgets": [
            "36b8877ee28d4ba688fbf1564643f8d5",
            "8171ef2262064a8da5707c2dc3949e79",
            "41b603d91dba4cbcb5c0d09e82fb3eba",
            "e518c2a4048b4796a8e31af06ed39d8e",
            "14098273ad494549ba282756de7b5f9e",
            "492e5d9d9df94a119b30243d6ae09f55",
            "c28d8915b8e7411585a4a03fede0bc72",
            "bc6c1e5bdf7947faa65146fcb730f7a3",
            "ee51faa2bebc4d3b8e2d5b0fe80716d4",
            "6e7b17b7f2714b7e9e847a687fe92e66",
            "d782336cbdb743c2adb1bbe92c5b0739",
            "c8a0f8cd248c44d388b90bda5ee90747",
            "9fbb46166dcd45dcb604a27052c412b9",
            "180b24cbd6dc423195417316f8232ad7",
            "21e1130707a94d3caea7e61c7be958df",
            "516f463d28e5452cbfefca9122b95d35",
            "eee91ebac1c34bb78c82d0596188da38",
            "e9caa74fbcd241e893006c3fd16c63f9",
            "7ddacf7fe4874d7989643e915329a700",
            "c8562977b31243b79c63ba524d38b1ae",
            "3b425ca2df054e40a03e6fe84db4095d",
            "bfce75228d9d4fb29913d50094eed968",
            "d53800e82b884a86bfa8cf8f57ce0545",
            "2826d059c3474f019bf578dafb5be19b",
            "d2bbd97d2f414265b018f227dd704eb6",
            "afc2d40152ea447e8d4dafd1952f4121",
            "aa0f35b98ef44cb7aceae9144d87f1ba",
            "76bf3802dfb940ccba3ae7b15477e9ac",
            "278e13710a0e46f38ab6046ea8c2ee50",
            "14f169d66cd54c0294d6f1788dc13dc3",
            "edfe7263d1214e6d84e90bd46012f91f",
            "9440e4713f874ceda4afeafdbd81eed4",
            "b3de2d7cdc684f67b73ca6e3bb045bfa",
            "05af3cc226564ca381006b4e3685efef",
            "561c17cfd9e949a196a63f78281e387c",
            "43a4b3d5bb094cf9af09a61f141e0011",
            "c4ba63890e0f4672899ecd2e628b4b39",
            "80377ed170b04a96b4d8fcba16033366",
            "72be770cc8b74113b24f00185a2da652",
            "e76e87ff20ef4dd88fc6d99721b03f3e",
            "dd0642a14ca547cb9486e2f7d5354416",
            "2579ccc1f5fc458ea79e9cbd4bedfbde",
            "62dd7864f4904ea9b062e3efacef1781",
            "cc1e1bd747f9439c84740c1679254edb"
          ]
        },
        "id": "UBMXK8IpeVbV",
        "outputId": "00555a13-029e-423b-c3b3-7b5b57cf5740"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "VBox(children=(Button(description='Raíces', style=ButtonStyle()), Button(description='Interpoladores', style=B…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "36b8877ee28d4ba688fbf1564643f8d5"
            }
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "qPkPyaAxhSlU"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "ghHp5t4sguVp"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}